#Importing module with name "t"
import turtle as t
import random as r

#turt Program
wn = t.Screen()
wn.bgcolor("gray")
wn.screensize(1500,800)
wn.addshape('santa.gif')
wn.addshape('wreath.gif')
wn.addshape('stick.gif')
wn.addshape('hat.gif')

#picture
santa = t.Turtle()
santa.shape('santa.gif')
santa.penup()
santa.goto(300,-300)

#object = module.Constructor() - makes 1 turt
for turtles in range(125):
    snow = t.Turtle()
    snow.shape("circle")
    snow.color("white")
    snow.teleport(x=(r.randint(-750,750)),y=(r.randint(-400,400)))
#put into window
#present
pres=t.Turtle()
pres.speed(0)
pres.teleport(-400,-350)
pres.fillcolor("red")
pres.begin_fill()
pres.fd(90)
pres.lt(90)
pres.fd(100)
pres.lt(90)
pres.fd(90)
pres.lt(90)
pres.fd(100)
pres.lt(90)
pres.end_fill()

pres.teleport(-290,-350)
pres.fillcolor("red")
pres.begin_fill()
pres.fd(90)
pres.lt(90)
pres.fd(100)
pres.lt(90)
pres.fd(90)
pres.lt(90)
pres.fd(100)
pres.lt(90)
pres.end_fill()

pres.teleport(-400,-230)
pres.fillcolor("red")
pres.begin_fill()
pres.fd(90)
pres.lt(90)
pres.fd(100)
pres.lt(90)
pres.fd(90)
pres.lt(90)
pres.fd(100)
pres.lt(90)
pres.end_fill()

pres.teleport(-290,-230)
pres.fillcolor("red")
pres.begin_fill()
pres.fd(90)
pres.lt(90)
pres.fd(100)
pres.lt(90)
pres.fd(90)
pres.lt(90)
pres.fd(100)
pres.lt(90)
pres.end_fill()



pres.teleport(-310,-350)
pres.fillcolor("green")
pres.begin_fill()
pres.fd(20)
pres.lt(90)
pres.fd(220)
pres.lt(90)
pres.fd(20)
pres.lt(90)
pres.fd(220)
pres.lt(90)
pres.end_fill()

pres.teleport(-400,-250)
pres.fillcolor("green")
pres.begin_fill()
pres.fd(200)
pres.lt(90)
pres.fd(20)
pres.lt(90)
pres.fd(200)
pres.lt(90)
pres.fd(20)
pres.lt(90)
pres.end_fill()
pres.rt(270)
pres.teleport(-305,-100)
pres.pensize(30)
pres.pencolor('green')
pres.pendown()

for i in range(2):
    pres.circle(40,90)
    pres.circle(40//2,90)
pres.teleport(-275,-120)
pres.rt(90)
for i in range(2):
    pres.circle(40,90)
    pres.circle(40//2,90)

#
#christmas tree
tree = t.Turtle()
tree.fillcolor("brown")
tree.begin_fill()
tree.teleport(-25,-300)
tree.fd(50)
tree.lt(90)
tree.fd(100)
tree.lt(90)
tree.fd(50)
tree.lt(90)
tree.fd(100)
tree.end_fill()

tree.fillcolor('green')
tree.begin_fill()
tree.teleport(-100,-200)
tree.lt(90)
tree.fd(200)
tree.lt(135)
tree.fd(145)
tree.lt(90)
tree.fd(145)
tree.lt(45)
tree.end_fill()

tree.begin_fill()
tree.teleport(-90,-130)
tree.lt(90)
tree.fd(180)
tree.lt(135)
tree.fd(135)
tree.lt(90)
tree.fd(135)
tree.lt(45)
tree.end_fill()
    
tree.begin_fill()
tree.teleport(-80,-70)
tree.lt(90)
tree.fd(160)
tree.lt(135)
tree.fd(120)
tree.lt(90)
tree.fd(120)
tree.lt(45)
tree.end_fill()
#ornaments

ornColors = ["red","green","red","yellow","black","blue","red","green","blue"]
for color in ornColors:
    orn=t.Turtle()
    orn.fillcolor(color)
    orn.shape("circle")
    orn.teleport(x=(r.randint(-50,50)),y=(r.randint(-200,15)))
#snowman
snowman = t.Turtle()
snowman.speed(0)
snowman.teleport(-600,-280)
snowman.fillcolor("white")
snowman.begin_fill()
for i in range(360):
    snowman.fd(1)
    snowman.rt(1)
for i in range(180):
    snowman.fd(1)
    snowman.lt(2)
snowman.end_fill()
snowman.fillcolor("black")
snowman.begin_fill()
snowman.teleport(-600,-250)
for i in range(45):
    snowman.fd(1)
    snowman.lt(8)
snowman.penup()
snowman.fd(20)
snowman.pendown()
for i in range(45):
    snowman.fd(1)
    snowman.lt(8)
snowman.end_fill()
snowman.fillcolor("orange")
snowman.begin_fill()
snowman.teleport(-600,-260)
snowman.fd(45)
snowman.rt(160)
snowman.fd(30)
snowman.rt(30)
snowman.fd(20)
snowman.end_fill()
#star
#mc
write = t.Turtle()
write.teleport(-150,200)
write.write("Merry Christmas!",font=('gill sans',50,'normal'))

#
star = t.Turtle()
star.teleport(7,50)
star.fillcolor("yellow")
star.begin_fill()
star.rt(10)
for i in range(5):
        star.forward(25)
        star.right(120)
        star.forward(25)
        star.right(72 - 120)
star.end_fill()
#last line
hat = t.Turtle()
hat.shape('hat.gif')
hat.teleport(-150,195)
stick = t.Turtle()
stick.shape('stick.gif')
stick.teleport(-150,70)
wreath = t.Turtle()
wreath.shape('wreath.gif')
wreath.teleport(-500,300)

wn.mainloop()