print("Mad Libs 2023 V1")
print()
input("Give me an Action Word")
input("Give me a Noun")
input("Give me a verb")
input("Give me a action word")
input("Give me a verb")
input("Give me a Noun")
input("Give me a action word")
input("Give me a adjective")
input("Give me a Noun")
input("Give me a Noun")
input("Give me a Noun")
input("Give me a Noun")
